#!/usr/bin/env bash

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
export HISTSIZE=1000
export HISTFILESIZE=2000

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# fixes screen size when using chrome remote desktop on chromebook.
export CHROME_REMOTE_DESKTOP_DEFAULT_DESKTOP_SIZES="1920x1080"

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

